git_repo_link: "https://github.com/aleksanderkaasik/RESTingCertCall.git"

project_name: "pki-cert-api-name"
project_path: "/var/opt/{{ project_name }}"

nodejs_hostname:
nodejs_port:

ca_cert_passphrase:

country:
country_state:
city:
organization:
organizational_unit:
common_name: